apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  checksum: sha256:9f95c5b8ec8ab8276469ed6db61549b704925f650e61ea532e41bee60adf6d6b
  deployment:
    spec:
      template:
        spec:
          containers:
            - env:
                - name: var1
                  value: value
                - name: var2
                  value: value2
              name: helloworld
  deps: |-
    {
      "name": "helloworld",
      "main": "helloworld.js",
      "license": "Unlicense",
      "dependencies": {},
      "devDependencies": {
        "gulp": "^4.0.2",
        "yaml": "^1.7.2"
      }
    }
  function: |
    module.exports = {
      main: function(event, context) {
        return "hello world 1234";
      }
    };
  runtime: nodejs8
  type: HTTP
  handler: handler.main
  function-content-type: text
